# Generated by Django 4.0.3 on 2022-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
