# Generated by Django 4.0.3 on 2022-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_message_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
