# Generated by Django 4.0.3 on 2022-05-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_userimage_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='image_model',
        ),
    ]
